package co.in.popcon.hibernate;
// Generated May 29, 2016 6:12:54 PM by Hibernate Tools 4.3.1



/**
 * FirstSubcategory generated by hbm2java
 */
public class FirstSubcategory  implements java.io.Serializable {


     private Integer id;
     private int mainCategoryId;
     private String name;

    public FirstSubcategory() {
    }

    public FirstSubcategory(int mainCategoryId, String name) {
       this.mainCategoryId = mainCategoryId;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMainCategoryId() {
        return this.mainCategoryId;
    }
    
    public void setMainCategoryId(int mainCategoryId) {
        this.mainCategoryId = mainCategoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


