package co.in.popcon.hibernate;
// Generated May 29, 2016 6:12:54 PM by Hibernate Tools 4.3.1



/**
 * ProductSizeStockByColor generated by hbm2java
 */
public class ProductSizeStockByColor  implements java.io.Serializable {


     private Integer id;
     private int productSizeId;
     private int productByColourId;
     private int stock;

    public ProductSizeStockByColor() {
    }

    public ProductSizeStockByColor(int productSizeId, int productByColourId, int stock) {
       this.productSizeId = productSizeId;
       this.productByColourId = productByColourId;
       this.stock = stock;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getProductSizeId() {
        return this.productSizeId;
    }
    
    public void setProductSizeId(int productSizeId) {
        this.productSizeId = productSizeId;
    }
    public int getProductByColourId() {
        return this.productByColourId;
    }
    
    public void setProductByColourId(int productByColourId) {
        this.productByColourId = productByColourId;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }




}


