package co.in.popcon.hibernate;
// Generated May 29, 2016 6:12:54 PM by Hibernate Tools 4.3.1



/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail  implements java.io.Serializable {


     private Integer id;
     private int mainCategoryId;
     private int firstSubcategoryId;
     private int secondSubcategoryId;
     private String searchTag;
     private String productDetail;
     private String materialDetail;
     private String care;
     private int sellingPrice;
     private int displayPrice;
     private String productCode;

    public ProductDetail() {
    }

    public ProductDetail(int mainCategoryId, int firstSubcategoryId, int secondSubcategoryId, String searchTag, String productDetail, String materialDetail, String care, int sellingPrice, int displayPrice, String productCode) {
       this.mainCategoryId = mainCategoryId;
       this.firstSubcategoryId = firstSubcategoryId;
       this.secondSubcategoryId = secondSubcategoryId;
       this.searchTag = searchTag;
       this.productDetail = productDetail;
       this.materialDetail = materialDetail;
       this.care = care;
       this.sellingPrice = sellingPrice;
       this.displayPrice = displayPrice;
       this.productCode = productCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMainCategoryId() {
        return this.mainCategoryId;
    }
    
    public void setMainCategoryId(int mainCategoryId) {
        this.mainCategoryId = mainCategoryId;
    }
    public int getFirstSubcategoryId() {
        return this.firstSubcategoryId;
    }
    
    public void setFirstSubcategoryId(int firstSubcategoryId) {
        this.firstSubcategoryId = firstSubcategoryId;
    }
    public int getSecondSubcategoryId() {
        return this.secondSubcategoryId;
    }
    
    public void setSecondSubcategoryId(int secondSubcategoryId) {
        this.secondSubcategoryId = secondSubcategoryId;
    }
    public String getSearchTag() {
        return this.searchTag;
    }
    
    public void setSearchTag(String searchTag) {
        this.searchTag = searchTag;
    }
    public String getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }
    public String getMaterialDetail() {
        return this.materialDetail;
    }
    
    public void setMaterialDetail(String materialDetail) {
        this.materialDetail = materialDetail;
    }
    public String getCare() {
        return this.care;
    }
    
    public void setCare(String care) {
        this.care = care;
    }
    public int getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(int sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public int getDisplayPrice() {
        return this.displayPrice;
    }
    
    public void setDisplayPrice(int displayPrice) {
        this.displayPrice = displayPrice;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }




}


