package co.in.popcon.hibernate;
// Generated May 29, 2016 6:12:54 PM by Hibernate Tools 4.3.1



/**
 * ProductByColourImages generated by hbm2java
 */
public class ProductByColourImages  implements java.io.Serializable {


     private Integer id;
     private int productByColourId;
     private String image;

    public ProductByColourImages() {
    }

    public ProductByColourImages(int productByColourId, String image) {
       this.productByColourId = productByColourId;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getProductByColourId() {
        return this.productByColourId;
    }
    
    public void setProductByColourId(int productByColourId) {
        this.productByColourId = productByColourId;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


