package co.in.popcon.hibernate;
// Generated May 29, 2016 6:12:54 PM by Hibernate Tools 4.3.1



/**
 * SecondSubcategory generated by hbm2java
 */
public class SecondSubcategory  implements java.io.Serializable {


     private Integer id;
     private int firstSubcategoryId;
     private String name;

    public SecondSubcategory() {
    }

    public SecondSubcategory(int firstSubcategoryId, String name) {
       this.firstSubcategoryId = firstSubcategoryId;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFirstSubcategoryId() {
        return this.firstSubcategoryId;
    }
    
    public void setFirstSubcategoryId(int firstSubcategoryId) {
        this.firstSubcategoryId = firstSubcategoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


