package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FirstSubcategory generated by hbm2java
 */
public class FirstSubcategory  implements java.io.Serializable {


     private int id;
     private MainCategory mainCategory;
     private String name;
     private Set<ProductDetail> productDetails = new HashSet<ProductDetail>(0);
     private Set<SecondSubcategory> secondSubcategories = new HashSet<SecondSubcategory>(0);

    public FirstSubcategory() {
    }

	
    public FirstSubcategory(int id, MainCategory mainCategory, String name) {
        this.id = id;
        this.mainCategory = mainCategory;
        this.name = name;
    }
    public FirstSubcategory(int id, MainCategory mainCategory, String name, Set<ProductDetail> productDetails, Set<SecondSubcategory> secondSubcategories) {
       this.id = id;
       this.mainCategory = mainCategory;
       this.name = name;
       this.productDetails = productDetails;
       this.secondSubcategories = secondSubcategories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MainCategory getMainCategory() {
        return this.mainCategory;
    }
    
    public void setMainCategory(MainCategory mainCategory) {
        this.mainCategory = mainCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ProductDetail> getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set<ProductDetail> productDetails) {
        this.productDetails = productDetails;
    }
    public Set<SecondSubcategory> getSecondSubcategories() {
        return this.secondSubcategories;
    }
    
    public void setSecondSubcategories(Set<SecondSubcategory> secondSubcategories) {
        this.secondSubcategories = secondSubcategories;
    }




}


