package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MainCategory generated by hbm2java
 */
public class MainCategory  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<ProductDetail> productDetails = new HashSet<ProductDetail>(0);
     private Set<FirstSubcategory> firstSubcategories = new HashSet<FirstSubcategory>(0);

    public MainCategory() {
    }

	
    public MainCategory(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public MainCategory(int id, String name, Set<ProductDetail> productDetails, Set<FirstSubcategory> firstSubcategories) {
       this.id = id;
       this.name = name;
       this.productDetails = productDetails;
       this.firstSubcategories = firstSubcategories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ProductDetail> getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set<ProductDetail> productDetails) {
        this.productDetails = productDetails;
    }
    public Set<FirstSubcategory> getFirstSubcategories() {
        return this.firstSubcategories;
    }
    
    public void setFirstSubcategories(Set<FirstSubcategory> firstSubcategories) {
        this.firstSubcategories = firstSubcategories;
    }




}


