package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail  implements java.io.Serializable {


     private int id;
     private FirstSubcategory firstSubcategory;
     private MainCategory mainCategory;
     private SecondSubcategory secondSubcategory;
     private String searchTag;
     private String productDetail;
     private String materialDetail;
     private String care;
     private int sellingPrice;
     private int displayPrice;
     private String productCode;
     private Set<ProductSize> productSizes = new HashSet<ProductSize>(0);
     private Set<ProductByColour> productByColours = new HashSet<ProductByColour>(0);

    public ProductDetail() {
    }

	
    public ProductDetail(int id, FirstSubcategory firstSubcategory, MainCategory mainCategory, SecondSubcategory secondSubcategory, String searchTag, String productDetail, String materialDetail, String care, int sellingPrice, int displayPrice, String productCode) {
        this.id = id;
        this.firstSubcategory = firstSubcategory;
        this.mainCategory = mainCategory;
        this.secondSubcategory = secondSubcategory;
        this.searchTag = searchTag;
        this.productDetail = productDetail;
        this.materialDetail = materialDetail;
        this.care = care;
        this.sellingPrice = sellingPrice;
        this.displayPrice = displayPrice;
        this.productCode = productCode;
    }
    public ProductDetail(int id, FirstSubcategory firstSubcategory, MainCategory mainCategory, SecondSubcategory secondSubcategory, String searchTag, String productDetail, String materialDetail, String care, int sellingPrice, int displayPrice, String productCode, Set<ProductSize> productSizes, Set<ProductByColour> productByColours) {
       this.id = id;
       this.firstSubcategory = firstSubcategory;
       this.mainCategory = mainCategory;
       this.secondSubcategory = secondSubcategory;
       this.searchTag = searchTag;
       this.productDetail = productDetail;
       this.materialDetail = materialDetail;
       this.care = care;
       this.sellingPrice = sellingPrice;
       this.displayPrice = displayPrice;
       this.productCode = productCode;
       this.productSizes = productSizes;
       this.productByColours = productByColours;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FirstSubcategory getFirstSubcategory() {
        return this.firstSubcategory;
    }
    
    public void setFirstSubcategory(FirstSubcategory firstSubcategory) {
        this.firstSubcategory = firstSubcategory;
    }
    public MainCategory getMainCategory() {
        return this.mainCategory;
    }
    
    public void setMainCategory(MainCategory mainCategory) {
        this.mainCategory = mainCategory;
    }
    public SecondSubcategory getSecondSubcategory() {
        return this.secondSubcategory;
    }
    
    public void setSecondSubcategory(SecondSubcategory secondSubcategory) {
        this.secondSubcategory = secondSubcategory;
    }
    public String getSearchTag() {
        return this.searchTag;
    }
    
    public void setSearchTag(String searchTag) {
        this.searchTag = searchTag;
    }
    public String getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }
    public String getMaterialDetail() {
        return this.materialDetail;
    }
    
    public void setMaterialDetail(String materialDetail) {
        this.materialDetail = materialDetail;
    }
    public String getCare() {
        return this.care;
    }
    
    public void setCare(String care) {
        this.care = care;
    }
    public int getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(int sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public int getDisplayPrice() {
        return this.displayPrice;
    }
    
    public void setDisplayPrice(int displayPrice) {
        this.displayPrice = displayPrice;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public Set<ProductSize> getProductSizes() {
        return this.productSizes;
    }
    
    public void setProductSizes(Set<ProductSize> productSizes) {
        this.productSizes = productSizes;
    }
    public Set<ProductByColour> getProductByColours() {
        return this.productByColours;
    }
    
    public void setProductByColours(Set<ProductByColour> productByColours) {
        this.productByColours = productByColours;
    }




}


