package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductByColour generated by hbm2java
 */
public class ProductByColour  implements java.io.Serializable {


     private int id;
     private ProductDetail productDetail;
     private String title;
     private String colourName;
     private String hexCode;
     private Set<ProductByColourImages> productByColourImageses = new HashSet<ProductByColourImages>(0);
     private Set<ProductSizeStockByColor> productSizeStockByColors = new HashSet<ProductSizeStockByColor>(0);

    public ProductByColour() {
    }

	
    public ProductByColour(int id, ProductDetail productDetail, String title, String colourName, String hexCode) {
        this.id = id;
        this.productDetail = productDetail;
        this.title = title;
        this.colourName = colourName;
        this.hexCode = hexCode;
    }
    public ProductByColour(int id, ProductDetail productDetail, String title, String colourName, String hexCode, Set<ProductByColourImages> productByColourImageses, Set<ProductSizeStockByColor> productSizeStockByColors) {
       this.id = id;
       this.productDetail = productDetail;
       this.title = title;
       this.colourName = colourName;
       this.hexCode = hexCode;
       this.productByColourImageses = productByColourImageses;
       this.productSizeStockByColors = productSizeStockByColors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getColourName() {
        return this.colourName;
    }
    
    public void setColourName(String colourName) {
        this.colourName = colourName;
    }
    public String getHexCode() {
        return this.hexCode;
    }
    
    public void setHexCode(String hexCode) {
        this.hexCode = hexCode;
    }
    public Set<ProductByColourImages> getProductByColourImageses() {
        return this.productByColourImageses;
    }
    
    public void setProductByColourImageses(Set<ProductByColourImages> productByColourImageses) {
        this.productByColourImageses = productByColourImageses;
    }
    public Set<ProductSizeStockByColor> getProductSizeStockByColors() {
        return this.productSizeStockByColors;
    }
    
    public void setProductSizeStockByColors(Set<ProductSizeStockByColor> productSizeStockByColors) {
        this.productSizeStockByColors = productSizeStockByColors;
    }




}


