package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1



/**
 * ProductByColourImages generated by hbm2java
 */
public class ProductByColourImages  implements java.io.Serializable {


     private int id;
     private ProductByColour productByColour;
     private String image;

    public ProductByColourImages() {
    }

    public ProductByColourImages(int id, ProductByColour productByColour, String image) {
       this.id = id;
       this.productByColour = productByColour;
       this.image = image;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ProductByColour getProductByColour() {
        return this.productByColour;
    }
    
    public void setProductByColour(ProductByColour productByColour) {
        this.productByColour = productByColour;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


