package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductSize generated by hbm2java
 */
public class ProductSize  implements java.io.Serializable {


     private int id;
     private ProductDetail productDetail;
     private String sizeName;
     private Set<ProductSizeStockByColor> productSizeStockByColors = new HashSet<ProductSizeStockByColor>(0);

    public ProductSize() {
    }

	
    public ProductSize(int id, ProductDetail productDetail, String sizeName) {
        this.id = id;
        this.productDetail = productDetail;
        this.sizeName = sizeName;
    }
    public ProductSize(int id, ProductDetail productDetail, String sizeName, Set<ProductSizeStockByColor> productSizeStockByColors) {
       this.id = id;
       this.productDetail = productDetail;
       this.sizeName = sizeName;
       this.productSizeStockByColors = productSizeStockByColors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getSizeName() {
        return this.sizeName;
    }
    
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }
    public Set<ProductSizeStockByColor> getProductSizeStockByColors() {
        return this.productSizeStockByColors;
    }
    
    public void setProductSizeStockByColors(Set<ProductSizeStockByColor> productSizeStockByColors) {
        this.productSizeStockByColors = productSizeStockByColors;
    }




}


