package co.in.popcon;
// Generated May 29, 2016 4:19:38 PM by Hibernate Tools 4.3.1



/**
 * ProductSizeStockByColor generated by hbm2java
 */
public class ProductSizeStockByColor  implements java.io.Serializable {


     private int id;
     private ProductByColour productByColour;
     private ProductSize productSize;
     private int stock;

    public ProductSizeStockByColor() {
    }

    public ProductSizeStockByColor(int id, ProductByColour productByColour, ProductSize productSize, int stock) {
       this.id = id;
       this.productByColour = productByColour;
       this.productSize = productSize;
       this.stock = stock;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ProductByColour getProductByColour() {
        return this.productByColour;
    }
    
    public void setProductByColour(ProductByColour productByColour) {
        this.productByColour = productByColour;
    }
    public ProductSize getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(ProductSize productSize) {
        this.productSize = productSize;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }




}


